#!/bin/sh -e
#
# Used by the parent makefile. Compare two CSS files and output
# result as YAML.
#
# 1. Name of the test in YAML output.
# 3. Input SCSS file.
# 4. Fixture CSS file.
# 5. True value.
# 6. False value.
#
# Boolean values are customizable so you can invert them to get an
# "unexpected" test for free.
#
# Example:
#
#     tools/test ruby_sass_3_4 output.3.4.css expected.css true false
#     tools/test libsass output.lib.css unexpected.css false true
#

name=$1; shift
input=$1; shift
expected=$1; shift
true=$1; shift
false=$1; shift

#
# Compile given SCSS file at given endpoint and match it against
# given fixture file.
#
# 1. SassMeister endpoint.
# 2. Input SCSS file.
# 3. Fixture CSS file.
#
check() {
    diff \
        --ignore-space-change \
        --ignore-blank-lines \
        "$input" "$expected" > /dev/null
}

printf "    %s: " "$name"
check && echo "$true" || echo "$false"
